# Oefening: Cross-validatie

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Lees de gegevens
train_data = pd.read_csv('../data/train.csv', index_col='Id')
test_data = pd.read_csv('../data/test.csv', index_col='Id')

# Verwijder rijen met ontbrekend doel, scheid doel van voorspellers
train_data.dropna(axis=0, subset=['SalePrice'], inplace=True)
y = train_data.SalePrice
train_data.drop(['SalePrice'], axis=1, inplace=True)

# Selecteer alleen numerieke kolommen
numerieke_kolommen = [cname for cname in train_data.columns if train_data[cname].dtype in ['int64', 'float64']]
X = train_data[numerieke_kolommen].copy()
X_test = test_data[numerieke_kolommen].copy()

In [2]:
X.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageArea,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
Id,,,,,,,,,,,,,,,,,,,,,
1,60,65.0,8450,7,5,2003,2003,196.0,706,0,...,548,0,61,0,0,0,0,0,2,2008
2,20,80.0,9600,6,8,1976,1976,0.0,978,0,...,460,298,0,0,0,0,0,0,5,2007
3,60,68.0,11250,7,5,2001,2002,162.0,486,0,...,608,0,42,0,0,0,0,0,9,2008
4,70,60.0,9550,7,5,1915,1970,0.0,216,0,...,642,0,35,272,0,0,0,0,2,2006
5,60,84.0,14260,8,5,2000,2000,350.0,655,0,...,836,192,84,0,0,0,0,0,12,2008

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer

mijn_pijpleiding = Pipeline(steps=[
   ('preprocessor', SimpleImputer()),
   ('model', RandomForestRegressor(n_estimators=50, random_state=0))
   ])

In [ ]:
from sklearn.model_selection import cross_val_score

# Vermenigvuldig met -1 omdat sklearn *negatieve* MAE berekent
scores = -1 * cross_val_score(mijn_pijpleiding, X, y, cv=5, scoring='neg_mean_absolute_error')

print("Gemiddelde MAE-score:", scores.mean())

## Stap 1: Schrijf een nuttige functie

In [ ]:
def get_score(n_estimators):
###Geef de gemiddelde MAE over 3 CV-vouwen van het willekeurige bosmodel terug.

### Trefwoordargument:
### n_estimators -- het aantal bomen in het bos

#####
# Vervang deze body met uw eigen code

## Stap 2: Test verschillende parameterwaarden

In [ ]:
resultaten = ____ # Uw code hier

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

plt.plot(list(results.keys()), list(results.values()))
plt.show()

## Stap 3: Vind de beste parameterwaarde

In [ ]:
n_estimators = #####